import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import logo from '../../assets/images/logo.png';
import { PrescriptionForm } from '../../components/prescription/PrescriptionForm';
import { useAppointments } from '../../hooks/useAppointments';
import { usePrescriptions } from '../../hooks/usePrescriptions';
import type { Appointment } from '../../types/appointment.types';
import type { CreatePrescriptionRequest } from '../../types/prescription.types';

type DoctorAppointment = Appointment & { patientId: number; patientName: string };
export function PrescriptionPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const { history, loading: appointmentsLoading, error: appointmentsError, fetchAppointmentHistory } = useAppointments(); const { loading: saving, error, addPrescription, clearError } = usePrescriptions(); const [patientId, setPatientId] = useState<number | null>(null); const [appointmentId, setAppointmentId] = useState<number | null>(null); const [success, setSuccess] = useState('');
  const appointments = history.filter((appointment): appointment is DoctorAppointment => typeof appointment.patientId === 'number' && typeof appointment.patientName === 'string' && appointment.status === 'completed');
  const patients = useMemo(() => Array.from(new Map(appointments.map((appointment) => [appointment.patientId, appointment.patientName])).entries()).map(([id, name]) => ({ id, name })), [appointments]); const patientAppointments = appointments.filter((appointment) => appointment.patientId === patientId);
  useEffect(() => { fetchAppointmentHistory(); }, [fetchAppointmentHistory]); useEffect(() => { const p = Number(params.get('patientId')); const a = Number(params.get('appointmentId')); if (Number.isInteger(p) && p > 0) setPatientId(p); if (Number.isInteger(a) && a > 0) setAppointmentId(a); }, [params]);
  async function create(payload: CreatePrescriptionRequest) { setSuccess(''); const prescription = await addPrescription(payload); if (prescription) setSuccess(`Prescription #${prescription.prescriptionId} was issued successfully.`); }
  const selectedPatient = patients.find((patient) => patient.id === patientId);
  return <main className="doctor-profile-shell"><aside className="doctor-profile-sidebar"><img src={logo} alt="Smart Clinic" /><p className="doctor-profile-role">DOCTOR PORTAL</p><nav aria-label="Doctor navigation"><button type="button" onClick={() => navigate('/doctor/profile')}>My profile</button><button type="button" className="avail-nav-active" onClick={() => navigate('/doctor/prescriptions')}>Prescriptions</button><button type="button" onClick={() => navigate('/doctor/availability')}>Availability</button></nav><button className="doctor-signout" type="button" onClick={() => { localStorage.removeItem('sc_token'); localStorage.removeItem('sc_user'); navigate('/login', { replace: true }); }}>Sign out</button></aside><section className="doctor-profile-content"><header className="doctor-profile-header"><span>Patient care</span><div className="doctor-avatar">Rx</div></header><div className="doctor-profile-page rx-page"><p className="doctor-profile-kicker">PRESCRIPTION MANAGEMENT</p><h1>Issue a Prescription</h1><p className="doctor-profile-intro">Create a clear medicine plan after a completed consultation.</p>{success && <p className="rx-notice success" role="status">{success}</p>}{error && <p className="rx-notice error" role="alert">{error}</p>}<section className="rx-selection"><h2>Completed appointment</h2>{appointmentsLoading ? <p>Loading your appointments...</p> : appointmentsError ? <p className="rx-notice error">{appointmentsError}</p> : patients.length === 0 ? <p>No completed appointments are available.</p> : <div className="rx-selection-grid"><label>Patient<select value={patientId || ''} onChange={(event) => { setSuccess(''); clearError(); setPatientId(event.target.value ? Number(event.target.value) : null); setAppointmentId(null); }}><option value="">Select a patient</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.name}</option>)}</select></label><label>Related appointment <span>Optional</span><select value={appointmentId || ''} disabled={!patientId} onChange={(event) => setAppointmentId(event.target.value ? Number(event.target.value) : null)}><option value="">No linked appointment</option>{patientAppointments.map((appointment) => <option key={appointment.appointmentId} value={appointment.appointmentId}>{new Date(appointment.appointmentDate).toLocaleDateString('en-GB')} · {appointment.startTime}</option>)}</select></label></div>}</section>{selectedPatient && <p className="rx-patient-summary">Preparing a prescription for <strong>{selectedPatient.name}</strong>.</p>}<PrescriptionForm patientId={patientId} appointmentId={appointmentId} saving={saving} onSubmit={create} /></div></section></main>;
}
